name: LAB 1 Workflow

on:
  push:

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje personalizado
        run: echo "Hola, este es mi primer workflow"

      - name: Listar contenido del repositorio
        run: ls -la
